### PR TITLE
feat: use pnpm and workspaces, dev duplicate

### PR DESCRIPTION
**Pull request by VividLemon**

### CODE REVIEW

**Comment by aceofwings** [comment]
going to run through dev and let you know if things are good.

**Comment by aceofwings** [comment]
Slightly confused, do we not need a vuepress config anymore? Just seeing some major functionality changes regarding docs.

**Comment by VividLemon** [comment]
> Slightly confused, do we not need a vuepress config anymore? Just seeing some major functionality changes regarding docs.

That's odd. It's supposed to be there... I'm not sure when or how it got deleted. Give me a bit and I'll reintroduce a fix.

**Comment by VividLemon** [comment]
The more I look into it, the more confused I get. I don't remember deleting those files... In fact, I remember fixing those files since some of the ts files used extraneous imports that could have been gotten from vuepress package directly and I needed to do it again. 🤔 Very odd. Perhaps I'm just dumb. Anyways, check and see if that looks more correct. @aceofwings

**Comment by VividLemon** [comment]
@aceofwings the menu icon overlaps bv icon for the docs on mobile

**Pull request closed without merging**
