### PR TITLE
Ability to extend sizes and variants (augmenting interfaces)

### PR DESCRIPTION
**Pull request by esl51**
BEGIN_COMMIT_OVERRIDE
feat: add the ability to extend certain built in types
docs: add info on how to extend types
END_COMMIT_OVERRIDE

PR for issue #790

Now we will be able to augment new interfaces:

**shims-bootstrap-vue-3.d.ts:**
```ts
import 'bootstrap-vue-3'

declare module 'bootstrap-vue-3/dist/types' {
  export interface BaseColorVariant {
    'purple': unknown
  }
  export interface BaseButtonVariant {
    'outline-purple': unknown
  }
  export interface BaseSize {
    'xl': unknown
  }
}
```
New values can be used:
```vue
<b-button variant="purple" size="xl">Extra large purple button</b-button>
<b-button variant="outline-purple">Outline purple button</b-button>
```

### CODE REVIEW

**Comment by VividLemon** [comment]
I have two major questions on this.

First, how does `export interface BaseColorVariant {` syntax work? It would almost make more sense that the code you posted overwrites the bases... But I've never use it like that. 

Second, is it a possibility to use `type` instead of `interface`? Is it possible to augment the types in the same style of syntax you have made, without the weirdness of making the interface?

**Comment by esl51** [comment]
> First, how does `export interface BaseColorVariant {` syntax work? It would almost make more sense that the code you posted overwrites the bases... But I've never use it like that.

First we define an interface with basic values (`properties`). It is only needed for later augmentation. We don't use the type of properties, so `unknown` type (perhaps there is a more elegant solution, but I can't think of one).
Then we define ButtonVariant type, which will be union type by interface properties (`keyof`).

> Second, is it a possibility to use `type` instead of `interface`? Is it possible to augment the types in the same style of syntax you have made, without the weirdness of making the interface?

No, augmentation of types is impossible. So I had to use interfaces to do it.

> Third, if the components themselves use ColorVariant, and you are modifying BaseColorVariant, how does that ultimately affect the components?

The BaseButtonVariant interface extends BaseColorVariant (and therefore includes all its properties). When BaseColorVariant is augmented, the properties will be added to BaseButtonVariant and then to ButtonVariant as well.

**Comment by VividLemon** [comment]
Would you be willing to make an update to the docs, somewhere, speaking about how to go about using this? It doesn't need to be very good, just a good enough placeholder that I don't forget how to use it later.

**Comment by esl51** [comment]
> Would you be willing to make an update to the docs, somewhere, speaking about how to go about using this? It doesn't need to be very good, just a good enough placeholder that I don't forget how to use it later.

Okay, I'll do it soon.

**Comment by sfe-efficy** [comment]
If we try to use a vue typescript checker like "vue-tsc" this code is not working property.
For example the BButton.vue.d.ts is taken from: node_modules/bootstrap-vue-3/dist/components/BButton/BButton.vue.d.ts

And the the definition for variant has the following:

image

So, the vue-tsc is going to use the types inside the original module instead of using our custom definition.
Maybe is a lack of configuration in my side for vue-tsc.

In tsconfig.json I'm including types:

image

I have a file defined in types/bootstrap-vue3/shims-bootstrap-vue-3.d.ts

With the content:

```ts
import "bootstrap-vue-3";

declare module "bootstrap-vue-3" {
    export interface BaseButtonVariant {
        orange: unknown;
    }
}
```

This is the error reported by vue-tsc:

```

src/components/base-button/base-button.vue:13:15 - error TS2322: Type '"orange"' is not assignable to type 'keyof BaseButtonVariant | undefined'.

13               variant="orange"
                 ~~~~~~~

  node_modules/bootstrap-vue-3/dist/components/BButton/BButton.vue.d.ts:375:5
    375     variant: keyof import("../../types").BaseButtonVariant;
            ~~~~~~~
    The expected type comes from property 'variant' which is declared here on type 'ComponentProps<DefineComponent<{ active: { type: PropType<Booleanish>; default: boolean; }; disabled: { type: PropType<Booleanish>; default: bool
ean; }; href: { type: StringConstructor; required: false; }; ... 19 more ...; to: { ...; }; }, ... 10 more ..., { ...; }>>'


Found 1 error in src/components/base-button/base-button.vue:13
```

And this is the example:

image

also the IDE is complaining.

**Comment by esl51** [comment]
> If we try to use a vue typescript checker like "vue-tsc" this code is not working property. 
Try to add this to your tsconfig:

```
files": [
    "./src/shims-bootstrap-vue-3.d.ts"
  ]
```

**Comment by esl51** [comment]
And you have an error in shims file on this line:

```ts
declare module 'bootstrap-vue-3/dist/types' {
```

**Comment by sfe-efficy** [comment]
> ```ts
>  export interface BaseButtonVariant {
>     'default'
>     'ghost-danger'
>   }
> ```

Thanks, the only problem was related with this.
I was trying to override a simple type (thinking if it was possible don't create an interface to avoid the redundant code), and I guess I was doing some invalid mix.

I don't really need to add the "file" section into tsconfig.json

**Pull request merged**
