### PR TITLE
Feature/toast3

### PR DESCRIPTION
**Pull request by aceofwings**
Hey there,

So the toasts now resolve as brought up in #283. I have also added the on hover pause.

Documentation is now cleaned up and the build now successfully completes. @cdmoro I recommend if you can build the docs and push them. Then we can discuss about moving the project to a repository that is more organization central.

### CODE REVIEW

**Comment by mariusa** [comment]
I still get 
```
$ npm run docs:build

> bootstrap-vue-3@0.1.6 docs:build
> npm exec --workspace=docs vuepress build .

info Initializing VuePress and preparing data...
⠸ Compiling with vite[vite]: Rollup failed to resolve import "bootstrap-vue-3/dist/bootstrap-vue-3.css" from ".vuepress/clientAppEnhance.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
✖ Compiling with vite - failed
```

**Comment by aceofwings** [comment]
Try building the package 
`npm run build`

then build the docs. There is still some odd issue with bootstrap dependency being tied to the btoas plugin....

**Comment by aceofwings** [comment]
if someone can figure out why `usetoast` in toast.md causes an error `ReferenceError: document is not defined`. I don't see any bootstrap dependencies. Once I remove let toast = useToast()... the build completes

**Comment by mariusa** [comment]
Note, this commit also changes package.json by adding bootstrap to dependencies. It should be only in peerDeps.
You might want to fork again this repo to start fresh.

> Try building the package
> npm run build
> then build the docs

Didn't work. I've fixed the deps, now getting another error:
```

✔ Compiling with vite - done
✖ Rendering pages - failed
ReferenceError: document is not defined
    at enableDismissTrigger (/home/marius/work/bootstrap-vue-3/docs/node_modules/bootstrap/dist/js/bootstrap.js:761:21)
    at /home/marius/work/bootstrap-vue-3/docs/node_modules/bootstrap/dist/js/bootstrap.js:856:3
    at /home/marius/work/bootstrap-vue-3/docs/node_modules/bootstrap/dist/js/bootstrap.js:7:83
    at Object.<anonymous> (/home/marius/work/bootstrap-vue-3/docs/node_modules/bootstrap/dist/js/bootstrap.js:10:3)
```

**Comment by aceofwings** [comment]
Will be creating a fix on a new branch. Problem is directives are being compiled in ssr context. Weird as the usetoast function is wrapped in a client only tag. Maybe there's a different approach to import external modules.

**Comment by cdmoro** [comment]
Hello there, I've rewritten the toast docs and I could build Vuepress, I copy the same approach as we have in `config.ts` file:

``` vue
<script setup lang='ts'>
import {ref, computed} from 'vue'
  
if (!__VUEPRESS_SSR__) {
  const {useToast} = await import('bootstrap-vue-3');

  let toast = useToast()

    let show1 = () => {toast.show({title: 'example title'})}
    let show2 = () => {toast.info({title: 'example title', body: "This is a toast"})}

    let variantshow1 = () => {toast.danger({title: 'Item Deleted'}, {pos: 'bottom-right'})}
    let variantshow2 = () => {toast.info({title: 'New Message', body: "This is a toast"}, {pos: 'bottom-right'})}
    let variantshow3 = () => {toast.warning({title: 'Warning for Item', body: "Please check list"},{pos: 'bottom-right'})}
    let variantshow4 = () => {toast.success({title: 'Event Created!', body: "Bootstrap Event"},{pos: 'bottom-right'})}
}
</script>
```

But when I serve the docs I have a lot of warns and errors in the console :disappointed: 

``` bash
runtime-core.esm-bundler.js?892f:38 [Vue warn]: resolveComponent can only be used in render() or setup().
```

``` bash
[Vue warn]: Unhandled error during execution of render function 
  at <BCard> 
  at <ClientOnly> 
  at <Button.html> 
  at <AsyncComponentWrapper> 
  at <Content> 
  at <Page key="/components/Button.html" > 
```

``` bash
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'isCE')
    at renderSlot (runtime-core.esm-bundler.js?892f:6561:1)
    at eval (bootstrap-vue-3.es.js?89cb:1264:1)
```

I'm a bit lost here, it's been a while since I've seen the documentation source code.

**Comment by aceofwings** [comment]
Update, 

I tried your approach but now get 
```
 ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")

with a failure.
```

**Pull request merged**
