### PR TITLE
docs: add in issue templates for GH

### PR DESCRIPTION
**Pull request by VividLemon**

### CODE REVIEW

**Comment by aceofwings** [comment]
Nice Nice, Before we merge this in I have a fix in the works for dev Docs. This includes making sure the vuepress docs follow the latest requirements. Still cannot figure out the issue between why the docs build in the root project directory as opposed to apps/docs/

**Comment by mariusa** [comment]
@aceofwings will you please merge when ready?

**Comment by VividLemon** [comment]
> Nice Nice, Before we merge this in I have a fix in the works for dev Docs. This includes making sure the vuepress docs follow the latest requirements. Still cannot figure out the issue between why the docs build in the root project directory as opposed to apps/docs/

If you were concerned about anything affecting the docs while you were changing things,  I would have been more concerned with the other pr that makes changes to the types page.

This pr only affects the .github directory. 

What do you mean, the docs build in the root?

**Comment by aceofwings** [comment]
@VividLemon , I moved all files to a docs folders within the root project directory ( where the .gitignore ). I am starting to think its the packaging tool resolving dependencies.

**Comment by VividLemon** [comment]
> @VividLemon , I moved all files to a docs folders within the root project directory ( where the .gitignore ). I am starting to think its the packaging tool resolving dependencies.

If you have it working, do you want to post a zip or branch

**Comment by aceofwings** [comment]
I do but its definitely not portable, currently narrowing down what changes in the environment which causes the error to occur.

**Pull request merged**
