### PR TITLE
add: table's slots head-top and head-sub

### PR DESCRIPTION
**Pull request by AlteraWeb**
table's slots head-top(without options) and head-sub (with options: key, label)

### CODE REVIEW

**Comment by mariusa** [comment]
Thanks!

**Comment by mariusa** [comment]
PS: would be simpler to issue PRs directly for `main` branch.

**Comment by AlteraWeb** [comment]
Thanks

**Comment by mariusa** [comment]
Hi, please see the issue in https://github.com/cdmoro/bootstrap-vue-3/pull/269

**Pull request merged**
