### PR TITLE
feat: support for library authors for nuxt3

### PR DESCRIPTION
**Pull request by messenjer**
Implements [support for library authors for nuxt3](https://v3.nuxtjs.org/guide/directory-structure/components/#library-authors)

# Create a Nuxt3 project

```
npx nuxi init nuxt-app
cd nuxt-app
npm install
npm run dev -- -o
```

# Install bootstrap-vue3 and boostrap

```
npm install bootstrap bootstrap-vue-3
```
# Configure your project

Open your `nuxt.config.ts` or `nuxt.config.js` file and configure your application to use `bootstrap-vue-3`. The components will be imported automatically as needed.

```javascript
import {defineNuxtConfig} from 'nuxt3'
export default defineNuxtConfig({
  modules: ['bootstrap-vue-3/nuxt'],
  css: ['bootstrap/dist/css/bootstrap.css'],
})
```

# Enjoy it in your app without import.

```vue
<template>
  <div>
    <BButton variant="primary">Primary</BButton>
    <BBadge variant="danger">Danger</BBadge>
  </div>
</template>
```

### CODE REVIEW

**Comment by JamesCullum** [comment]
I get the following error when following these instructions:

`Cannot start nuxt:  Package subpath './nuxt' is not defined by "exports" in C:\Users\Nicol\Desktop\gourmet-detectives\node_modules\bootstrap-vue-3\package.json    `

**Comment by messenjer** [comment]
Hello,

This is not yet in the latest release. We need to wait 0.1.12.

**Comment by JamesCullum** [comment]
@mariusa Is there a date on when the next version is planned to be released?

**Comment by mariusa** [comment]
Made a release now for you :)

**Pull request merged**
