### PR TITLE
feat: begin development of bootstrap-vue-3-icons

### PR DESCRIPTION
**Pull request by VividLemon**
# Describe the PR

A clear and concise description of what the pull request does.

## Small replication

If the change is large enough, a small replication can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [ ] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or have an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

**Comment by aceofwings** [comment]
Are we still looking to create the build script and separate exports for icon svgs?

**Comment by VividLemon** [comment]
> Are we still looking to create the build script and separate exports for icon svgs?

Don't know what the build script is. I'm not sure about the second either.

**Comment by aceofwings** [comment]
Well I can finalize that... if no one else is working on it. If you look into the original boostrap vue it is part of the icons package.

**Comment by VividLemon** [comment]
> Well I can finalize that... if no one else is working on it. If you look into the original boostrap vue it is part of the icons package.

Soon I will write tests and convert the render functions.

**Pull request merged**
