### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mariusa**

### CODE REVIEW

**Comment by mariusa** [comment]
@AlteraWeb 
Did you test this on your local env?
```
npm run dev
npm run test
```

See the above fail in App.vue.
Waiting for your fix in this PR. Thanks!

**Comment by AlteraWeb** [comment]
> @AlteraWeb Did you test this on your local env?
> 
> ```
> npm run dev
> npm run test
> ```
> 
> See the above fail in App.vue. Waiting for your fix in this PR. Thanks!

I so sorry, i fixed it in main. If it necessary I can resend in develop

**Comment by mariusa** [comment]
Please see the error in the test run showing at the end of this PR
https://github.com/cdmoro/bootstrap-vue-3/runs/5106905855?check_suite_focus=true
```
/home/runner/work/bootstrap-vue-3/bootstrap-vue-3/src/App.vue
Error:   [14](https://github.com/cdmoro/bootstrap-vue-3/runs/5106905855?check_suite_focus=true#step:5:14)61:16  error  'BFormSelect' is not defined  no-undef
```

How to reproduce:
```
$ git clone git@github.com:cdmoro/bootstrap-vue-3.git
Cloning into 'bootstrap-vue-3'...
remote: Enumerating objects: 4348, done.
remote: Counting objects: 100% (129/129), done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 4348 (delta 59), reused 69 (delta 26), pack-reused 4219
Receiving objects: 100% (4348/4348), 3.69 MiB | 3.32 MiB/s, done.
Resolving deltas: 100% (2791/2791), done.
[marius@fedora work/bd]$ cd bootstrap-vue-3/
[marius@fedora bd/bootstrap-vue-3]$ git checkout develop
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
Switched to a new branch 'develop'
[marius@fedora bd/bootstrap-vue-3]$ npm i
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated

> bootstrap-vue-3@0.1.2 prepare
> husky install && vite build

husky - Git hooks installed
vite v2.7.13 building for production...
✓ 172 modules transformed.
dist/bootstrap-vue-3.css     4.61 KiB / gzip: 1.27 KiB
dist/bootstrap-vue-3.es.js   381.31 KiB / gzip: 73.82 KiB
dist/bootstrap-vue-3.umd.js   205.76 KiB / gzip: 54.78 KiB

added 967 packages, and audited 968 packages in 1m

90 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[marius@fedora bd/bootstrap-vue-3]$ npm run test

> bootstrap-vue-3@0.1.2 test
> npm run test:lint && npm run test:unit


> bootstrap-vue-3@0.1.2 test:lint
> npm run lint


> bootstrap-vue-3@0.1.2 lint
> eslint --ext .js,.vue --ignore-path .gitignore --fix src


/home/marius/work/bd/bootstrap-vue-3/src/App.vue
  1461:16  error  'BFormSelect' is not defined  no-undef

/home/marius/work/bd/bootstrap-vue-3/src/components/BCarousel/BCarouselSlide.vue
  28:40  warning  'v-html' directive can lead to XSS attack  vue/no-v-html
  32:37  warning  'v-html' directive can lead to XSS attack  vue/no-v-html

/home/marius/work/bd/bootstrap-vue-3/src/components/BInputGroup/BInputGroup.vue
   7:38  warning  'v-html' directive can lead to XSS attack  vue/no-v-html
  16:37  warning  'v-html' directive can lead to XSS attack  vue/no-v-html

/home/marius/work/bd/bootstrap-vue-3/src/components/BPagination/BPagination.vue
  159:11  warning  'pageNumberfinal' is assigned a value but never used  @typescript-eslint/no-unused-vars

✖ 6 problems (1 error, 5 warnings)

```

**Pull request merged**
