### PR TITLE
FormCheckbox v-model support

### LINKED ISSUE #49: BFormCheckbox does not support v-model
the BFormCheckbox component does not support v-model

      <div>{{ vartocheck }}</div>
      <b-form-checkbox v-model="vartocheck">Default</b-form-checkbox>

and the the setup method in the script
  setup() {
    const vartocheck = ref(false);
    return {
      vartocheck
    }
});

### PR DESCRIPTION
**Pull request by jclijmans**
v-model support for FormCheckbox. It fixes #49 
v-model supports boolean, string values set in value/unchecked-value as well as an array.

The model binds to the standard modelValue prop, so I have removed the checked prop

Doc is also updated.
As soon as I can figure out how to use vue components or real javascript code in the markdow, I'll add live examples in the documentation

### CODE REVIEW

**Comment by cdmoro** [comment]
One thing, could you have a look at #46 please?

**Comment by jclijmans** [comment]
I have raised the issue because I think the current implementation is reversed.
I did not get a response from you that indeed it should be reversed.

If so, I'll take a look at reversing the plain property

**Comment by mariusa** [comment]
Thanks @jclijmans !

> as well as an array.

Does this mean #30 is no longer needed?

**Comment by jclijmans** [comment]
For checkboxes where you select multiple items out of an array, the grouping is not needed. See App.vue for an example

For radio buttons where you want 1 item selected out of the array. That doesn't work with the current implementation.
There is some contention between the different components all trying to update the single model

**Comment by mariusa** [comment]
Thanks for clarification!

**Pull request merged**
