### PR TITLE
revert: add back in app.vue in /package/bootstrap*

### PR DESCRIPTION
**Pull request by VividLemon**
The playground environment is great for simulating a user environment, however, as I have stated, it doesn't really work that well for developing components since playground only uses ./dist of the main package. It would need to be rebuilt constantly in order to see a good affect. There could be a workaround that I don't know about, or a better way in general.

Read the TODO in app.vue and make a discussion (or post on PR) if you think app.vue development area should be reverted or expanded like it was pre-pnpm/workspace commit, I thought the old app.vue was pretty bloated and messy, which is why I made the ./apps/playground more clean.

It could be possible to add in all of ./apps/playground features, but I didn't think I should bloat the src/components dir with dev stuff. (But I could make a src/components/dev folder or something to store them) and recreate the ./apps/playground like environment

### CODE REVIEW

**Comment by VividLemon** [comment]
If there aren't any thoughts on the above, I believe this branch could be full merged into main. There will probably a few issues, but none that I know of atm

**Comment by mariusa** [comment]
Totally agree! I noticed the same issues, but didn't have time to work out something better. Thank you!

**Comment by VividLemon** [comment]
> Totally agree! I noticed the same issues, but didn't have time to work out something better. Thank you!

What do you think the process should be for merging into main? Unless there are any objections to anyone else, the dev branch is pretty much done.

**Comment by mariusa** [comment]
Will you please open a PR to merge into main?

**Comment by VividLemon** [comment]
> Will you please open a PR to merge into main?

Can you try doing that? Before https://github.com/cdmoro/bootstrap-vue-3/pull/508 and when I had the option, it kept popping up with a `Pull request creation failed. Validation failed: You can't perform that action at this time.` Not really sure how to fix that.

**Comment by VividLemon** [comment]
I might just try a workaround and create a new branch, then request a new PR. I don't think I'm able to edit others PRs and when looking at the PR, it says there's conflicts, but doesn't show them. I'll try to figure it out in a different way.

**Pull request merged**
