### PR TITLE
chore!: vue considered peerDependency

### PR DESCRIPTION
**Pull request by VividLemon**
Release-As: 0.2.1

### CODE REVIEW

**Comment by VividLemon** [comment]
I'm hoping release-please will publish this version. I don't want to pollute a bunch of extra version numbers try to diagnose :/

**Comment by mariusa** [comment]
Hmm, no release PR this time

**Comment by VividLemon** [comment]
> Hmm, no release PR this time

https://github.com/cdmoro/bootstrap-vue-3/pull/522 Believe this is why. I think it only had to do with the fact that it was an empty commit causing the action to not run. Are you able to do a manual release to npm?

**Comment by mariusa** [comment]
Thanks!

Would prefer to wait for the next change which triggers release bot, so we can fully test everything.

**Comment by VividLemon** [comment]
> Thanks!
> 
> Would prefer to wait for the next change which triggers release bot, so we can fully test everything.

I can submit some of the finished components to bnav if you'd like

**Comment by mariusa** [comment]
> I can submit some of the finished components to bnav if you'd like. 

Yes please. 
Still not published at https://www.npmjs.com/package/bootstrap-vue-3 :(

**Comment by VividLemon** [comment]
> > I can submit some of the finished components to bnav if you'd like.
> 
> Yes please. Still not published at https://www.npmjs.com/package/bootstrap-vue-3 :(

Yes, I noticed that for some reason the if statements on actions are causing them to never run. https://github.com/cdmoro/bootstrap-vue-3/runs/7632822151?check_suite_focus=true . If the next actual commit that changes something doesn't cause them to fire, that means I have an issue I need to work out.

**Comment by mariusa** [comment]
Thanks for looking into it!

**Comment by mariusa** [comment]
Shall I merge https://github.com/cdmoro/bootstrap-vue-3/pull/524 or wait for some other changes?

**Comment by VividLemon** [comment]
> Shall I merge #524 or wait for some other changes?

It's up to you. I think it could be released primarily to see if the workflow is working properly. But I'm likely to have a few more components done by tomorrow.

**Comment by mariusa** [comment]
Ah, I was referring only to testing the workflows, especially publishing. Will merge now.

**Comment by mariusa** [comment]
It still doesn't publish at https://www.npmjs.com/package/bootstrap-vue-3

**Comment by VividLemon** [comment]
I left a question report to their github. A possible fix would be to remove the if statements outright and wait for their response to see if there's a better option.

**Comment by VividLemon** [comment]
I'm still waiting on the question I posted, but I realize that since I'm not concerned with the actual *status* of publishing to npm, rather only the workflow, I believe I can test out and try to figure out a solution on my own repository without bloating and waiting for you to review requests..

**Pull request merged**
