### PR TITLE
Spin button

### PR DESCRIPTION
**Pull request by aceofwings**
# Describe the PR

Port over SpinButton code and some test cases.  

Ill be considering putting docs in a separate mass update.

Feel free to take a look. Will be planning on merging in the coming week. 

## Small replication

If the change is large enough, a small replication can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [x] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or have an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

**Comment by VividLemon** [comment]
I'd prefer the component to be rewritten using `<template>`'s. I generally write tests first, attempt to get full code coverage, then make the change. In addition, I usually prefer to get rid of the bootstrap-vue utils code. But, if you would like to get it working, I can later on make the tests and rewrite to script setup and template. And, as much as possible remove attempts to call "window" for ssr. I'm aware that this is a draft.

**Comment by aceofwings** [comment]
> I'd prefer the component to be rewritten using `<template>`'s. I generally write tests first, attempt to get full code coverage, then make the change. In addition, I usually prefer to get rid of the bootstrap-vue utils code. But, if you would like to get it .......

I am going to complete the tests. You might have to elaborate on the utils part. I am going to move toward providing a functional component. The window stuff will not impact server side rendering as they are event listeners and will not present any effects on hydration and template rendering. Code acts as more of a polyfill which may not need to be necessary.

**Comment by VividLemon** [comment]
> You might have to elaborate on the utils part

Bootstrapvue has a util called arrayIncludes. Js has a method called Array.includes. why use their function?

**Comment by aceofwings** [comment]
> > You might have to elaborate on the utils part
> 
> Bootstrapvue has a util called arrayIncludes. Js has a method called Array.includes. why use their function?

interesting I did not know that.

**Comment by VividLemon** [comment]
> > > You might have to elaborate on the utils part
> > 
> > 
> > Bootstrapvue has a util called arrayIncludes. Js has a method called Array.includes. why use their function?
> 
> interesting I did not know that.

BV also does some other weird stuff, like making a function called mathMin that literally returns Math.min
`export const mathMin => Math.min` was an actual function for some reason

**Comment by aceofwings** [comment]
Yeah I have been moving away from the math utility's. I’ll update and check through ones that are not necessary

**Pull request closed without merging**
