### PR TITLE
Feature : Add Slots to Component Reference

### PR DESCRIPTION
**Pull request by aceofwings**
# Describe the PR

Add Slots to Component Reference 

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [x ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type**

### CODE REVIEW

**Comment by aceofwings** [comment]
One small problem,

BTable and its detail-row functionality does not work as intended. Seems that the row object does not have the reactive property established and therefore does not update on click but on page reload. Thought I could add something to fix it but I am sure there is a better way to establish the reactivity and I could not think of a way.

**Comment by VividLemon** [comment]
[CHANGELOG.md](https://github.com/cdmoro/bootstrap-vue-3/files/9536943/CHANGELOG.md)

There's a copy of mine. I deleted yours because I thought it would fix it showing that it was changed... It doesn't technically matter, if it manages to get deleted during a merge of this PR, I will add it back in manually.

**Comment by aceofwings** [comment]
> [CHANGELOG.md](https://github.com/cdmoro/bootstrap-vue-3/files/9536943/CHANGELOG.md)
> 
> There's a copy of mine. I deleted the one on this PR because I thought it would fix it showing that it was changed... It doesn't technically matter, if it manages to get deleted during a merge of this PR, I will add it back in manually.
> 
> Tbh I'm surprised I'm allowed to delete items from a PR that exist from a fork 🤔

Thanks, I saw that too and was wondering what was going on. I am going to just keep looking real quick to see what's going on with the row detail

**Comment by VividLemon** [comment]
> > [CHANGELOG.md](https://github.com/cdmoro/bootstrap-vue-3/files/9536943/CHANGELOG.md)
> > There's a copy of mine. I deleted the one on this PR because I thought it would fix it showing that it was changed... It doesn't technically matter, if it manages to get deleted during a merge of this PR, I will add it back in manually.
> > Tbh I'm surprised I'm allowed to delete items from a PR that exist from a fork 🤔
> 
> Thanks, I saw that too and was wondering what was going on. I am going to just keep looking real quick to see what's going on with the row detail

I mentioned to the active contributor that has been working on the table component, but he never messaged back. He has an active pr on the table, if you want, I'm sure he will eventually come to a solution, or you can message him yourself and you can both work to find a solution, or find it yourself.

**Comment by devhus** [comment]
> One small problem,
> 
> BTable and its detail-row functionality does not work as intended. Seems that the row object does not have the reactive property established and therefore does not update on click but on page reload. Thought I could add something to fix it but I am sure there is a better way to establish the reactivity and I could not think of a way.

Could you please post an example code to replace the issue? I need to understand where is the issue exactly

**Comment by VividLemon** [comment]
If detail-row has an issue, lets move it to an issue. Rather than multiple PRs

**Comment by devhus** [comment]
@aceofwings i just need the code you are using to see what i can do about it.

**Pull request merged**
