### PR TITLE
Upgrade vite and @vitejs/plugin-vue

### PR DESCRIPTION
**Pull request by jclijmans**
In response for #188
Don't know if that's al that's needed to have the ability to import individual components with tree-shaking

Updated vite to v2.6.12, updated @vitejs/plugin-vue to v1.9.3
Everything seems to work without errors or warnings

Did not update package.json because that specified 
vite 2.x.x
@vitejs/plugin-vue 1.x.x

If I need to update package.json, please let me know.

### CODE REVIEW

**Comment by axelthat2** [comment]
I don't think we need to do `bootstrap-vue-3["default"]`.

We could do just use it as,
```
import { BAlert } from "bootstrap-vue-3"
```

or if we want to use the whole library,
```
import BootstrapVue from "bootstrap-vue-3"
```

Am I missing something here?

**Comment by axelthat2** [comment]
We can set `build.rollupOptions.output.exports` to `named`.

https://github.com/rollup/rollup/issues/2106#issuecomment-377771639

**Comment by axelthat2** [comment]
@jclijmans What do you think of the above?

**Comment by jclijmans** [comment]
I'm sorry but I don't have experience with vite and rollup, so I don't know if this not just masks the problem.

The user should be able to use bootstrap-vue-3 by just doing as stated in the docs

```
import {createApp} from 'vue'
import BootstrapVue3 from 'bootstrap-vue-3'

import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue-3/dist/bootstrap-vue-3.css'

const app = createApp(App)
app.use(BootstrapVue3)
app.mount('#app')

```
If that's no problem, then I'm ok with this solution.

**Comment by axelthat2** [comment]
They can. I have tried already. One of the dev at rollup (https://github.com/rollup/rollup/issues/2106#issuecomment-377771639) already said the error message is slightly out of date. But I can verify again.

**Comment by jclijmans** [comment]
Ok, I'll create a PR for this

**Comment by axelthat2** [comment]
I believe the error message was for the CJS modules.

So, I think for CJS modules you have to do,

```
const BootstrapVue = require("bootstrap-vue-3")["default"]
```

Screen Shot 2021-10-31 at 8 09 15 PM

But we are not generating CJS so we are fine as you can see in the screenshot below.

Screen Shot 2021-10-31 at 8 10 07 PM

**Comment by jclijmans** [comment]
Ok, the fix is in.
@axelthat2 : can you test that it solves the problems with individual import of components please?

**Comment by axelthat2** [comment]
Sure!

**Comment by axelthat2** [comment]
@jclijmans Alright I have tested it and works.

**Comment by axelthat2** [comment]
I think you should also add this `export {plugin as BootstrapVue}`.

If you see here: https://bootstrap-vue.org/docs, you can also do,

```
import { BootstrapVue } from "bootstrap-vue"
```

**Comment by jclijmans** [comment]
Done, added 
`export {plugin as BootstrapVue3}`

so you have to do 
`import { BootstrapVue3 } from "bootstrap-vue-3"`

**Pull request merged**
