### PR TITLE
Add directive v-b-visible

### PR DESCRIPTION
**Pull request by bobaoapae**

### CODE REVIEW

**Comment by cdmoro** [comment]
Hello, let me ask you, I was looking for this `visible` behavior in Bootstrap and BootstrapVue and I couldn't find it. Where did you get it or what are your reasons to add it to this library?

**Comment by bobaoapae** [comment]
[https://bootstrap-vue.org/docs/directives/visible](https://bootstrap-vue.org/docs/directives/visible)

**Comment by bobaoapae** [comment]
i use this on my project, to load image only whe it become visible

**Comment by bobaoapae** [comment]
[https://github.com/bootstrap-vue/bootstrap-vue/tree/dev/src/directives/visible](https://github.com/bootstrap-vue/bootstrap-vue/tree/dev/src/directives/visible)

**Pull request merged**
