### PR TITLE
Update Toast.md

### PR DESCRIPTION
**Pull request by aceofwings**
Remove UseToast so docs can build

### CODE REVIEW

**Comment by cdmoro** [comment]
Hello there, I tried to build and I got the same error. Regarding your change, I believe more lines have to be commented or deleted.

**Comment by aceofwings** [comment]
I just fetched all recent changes and made the adjustment to make sure I am not going insane. Seems that removing the line above is the last thing in order to move the build forward.

**Comment by mariusa** [comment]
I'll also try after merge

**Comment by mariusa** [comment]
`bootstrap-vue-3]$ npm run docs:build` works now!

**Pull request merged**
